/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.18.0_1/nim/lib -o /Users/faysalahmed/Documents/projects/nim_projects/hello_nim/nimcache/hello_server.o /Users/faysalahmed/Documents/projects/nim_projects/hello_nim/nimcache/hello_server.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg;
typedef struct tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ;
typedef struct tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw;
typedef struct RootObj RootObj;
typedef struct tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg;
typedef struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA;
typedef struct tyTuple_kN8up2W6YKc5YA9avn5mV5w tyTuple_kN8up2W6YKc5YA9avn5mV5w;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ;
typedef struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg;
typedef struct tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww;
typedef struct Exception Exception;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ;
typedef struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA tyObject_Table_LLQadDAXEvd71UDdEc3lDA;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tySequence_JiteSJxrvz63iP2o9bcn2Sg tySequence_JiteSJxrvz63iP2o9bcn2Sg;
typedef struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ tyTuple_g1w83cyyBYiVU9c8WEJWnjQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_kN8up2W6YKc5YA9avn5mV5w {
NimStringDesc* Field0;
NI Field1;
NI Field2;
};
struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* path;
NimStringDesc* query;
NimStringDesc* anchor;
NIM_BOOL opaque;
};
struct tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ {
tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg* client;
tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA reqMethod;
tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers;
tyTuple_kN8up2W6YKc5YA9avn5mV5w protocol;
tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ url;
NimStringDesc* hostname;
NimStringDesc* body;
};
typedef struct {
N_NIMCALL_PTR(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_3cmVDZYspcmD9a16VGUFJoA;
struct tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw {
  RootObj Sup;
NI colonstate_;
tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ req1;
tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* retFuture2;
tyProc_3cmVDZYspcmD9a16VGUFJoA nameIterVar3;
};
struct tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww {
  RootObj Sup;
NI colonstate_;
tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future1;
tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw* colonup_;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, TM_sJmeuNYREbk30tBbLmMX4g_8) (void);
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, TM_sJmeuNYREbk30tBbLmMX4g_9) (void);
struct tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA {
  Exception Sup;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
typedef N_CLOSURE_PTR(void, TM_sJmeuNYREbk30tBbLmMX4g_11) (void);
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, ClP_0) (tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* request, void* ClE_0);
void* ClE_0;
} tyProc_9cYHoVsKEcSHuZkNJna2Tvg;
typedef N_CLOSURE_PTR(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, TM_sJmeuNYREbk30tBbLmMX4g_12) (tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* request, void* ClE_0);
struct tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw {
tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg* socket;
NIM_BOOL reuseAddr;
NIM_BOOL reusePort;
NI maxBody;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ {
tyProc_IIomJ6ptE6vfJ5zRbATgkQ function;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* next;
};
struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg {
  RootObj Sup;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ callbacks;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorStackTrace;
NimStringDesc* stackTrace;
NI id;
NimStringDesc* fromProc;
};
struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
};
typedef NIM_CHAR tyArray_QQGLPNVVwLhYjkngqAxXQQ[4001];
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg {
int fd;
NIM_BOOL closed;
NIM_BOOL isBuffered;
union{
struct {tyArray_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
} S1;
} isBufferedU;
NIM_BOOL isSsl;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType;
tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA {
tyObject_Table_LLQadDAXEvd71UDdEc3lDA* table;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA {
tySequence_JiteSJxrvz63iP2o9bcn2Sg* data;
NI counter;
};
struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ {
NI Field0;
NimStringDesc* Field1;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field2;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_JiteSJxrvz63iP2o9bcn2Sg {
  TGenericSeq Sup;
  tyTuple_g1w83cyyBYiVU9c8WEJWnjQ data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_sJmeuNYREbk30tBbLmMX4g_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw*, newAsyncHttpServer_8E3hcKWR9bMseKjk69aa6Aqw)(NIM_BOOL reuseAddr, NIM_BOOL reusePort, NI maxBody);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, cb_7z9cfXflyq3fFV9aWo0NvH9cg)(tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* req);
static N_NIMCALL(void, Marker_tyRef_B4LxXdb5z5tVUEzMUA22Tg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, newFuture_cw7L2Vu5pdfKvHqESZUwnA)(NimStringDesc* fromProc);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, Marker_tyRef_INo2UmKIotXHE9b9b2NJGwbg)(void* p, NI op);
N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, cbIter_TqaV9a1VSlZPZWTetcSzfdw)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, respond_F4lmxjjqUOo55CrHJJWOJw)(tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* req, NI code, NimStringDesc* content, tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers);
N_LIB_PRIVATE N_NIMCALL(void, read_EYgDXwwneJeAEUfXLUHmhg)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future);
N_LIB_PRIVATE N_NIMCALL(void, complete_mvHczm6KlNpTkVsXGCEbgg)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future);
N_LIB_PRIVATE N_CLOSURE(void, cb_continue_nWTMpJKJbxXeWUVE9bCQj9aA)(void* ClE_0);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(NIM_BOOL, finished_lnX3UZC8cmCUb7BzjNqokQasyncdispatch)(tyProc_3cmVDZYspcmD9a16VGUFJoA x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_ZDnEFECD9b9aKFsuVLxFyzkA_2)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_jn4eVK3zFIl4kShRnlTsCg)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(void, callbackeq__9c5z7ouO5bUylgKxaZoIuVg_2)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future, tyProc_IIomJ6ptE6vfJ5zRbATgkQ cb);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, fail_8buDkIPh9aRg7WBcB15eisA)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future, Exception* error);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, waitFor_VIKMhEBTNLqEA2ZGnacjrw)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* fut);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, serve_4qUYuAmkUBQy1ChRq42g5Q)(tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw* server, NU16 port, tyProc_9cYHoVsKEcSHuZkNJna2Tvg callback, NimStringDesc* address);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_heapqueueInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_heapqueueDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_listsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_listsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typetraitsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typetraitsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_optionsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_optionsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dequesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dequesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cstrutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cstrutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncfuturesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncfuturesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncstreamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncstreamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_kqueueInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_kqueueDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpcoreInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpcoreDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asynchttpserverInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asynchttpserverDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, hello_serverDatInit000)(void);
tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw* server_6AeqIvTsg3xq4ajrBvLQAQ;
extern TNimType NTI_WZMf6vpVUHkZoBQM9bgqK9aQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_Wqr0V9aQLrJgTvyTpMjKO9bw_;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ_;
extern TNimType NTI_1Wfxxtqzahm0R6lueM9aQmQ_;
extern TNimType NTI_zXD0JrbeCNyAaW4E6fB9aqg_;
extern TNimType NTI_3cmVDZYspcmD9a16VGUFJoA_;
TNimType NTI_B4LxXdb5z5tVUEzMUA22Tg_;
TNimType NTI_FC9cRk6qkw2JfD0NYbUD0ww_;
extern TNimType NTI_Mpt8aZ13tT2AYV71yyfHcA_;
TNimType NTI_INo2UmKIotXHE9b9b2NJGwbg_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_TmgWlPUbRr7iGD2UE1cu6A_;
extern TNimType NTI_8FC9arcap3s5ZtfMs75krtA_;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
STRING_LITERAL(TM_sJmeuNYREbk30tBbLmMX4g_4, "cb", 2);
STRING_LITERAL(TM_sJmeuNYREbk30tBbLmMX4g_6, "Hello World", 11);
STRING_LITERAL(TM_sJmeuNYREbk30tBbLmMX4g_10, "Async procedure ($1) yielded `nil`, are you await\'ing a `nil` F"
"uture\?", 69);
STRING_LITERAL(TM_sJmeuNYREbk30tBbLmMX4g_13, "", 0);
static N_NIMCALL(void, TM_sJmeuNYREbk30tBbLmMX4g_2)(void) {
	nimGCvisit((void*)server_6AeqIvTsg3xq4ajrBvLQAQ, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_B4LxXdb5z5tVUEzMUA22Tg)(void* p, NI op) {
	tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw* a;
	a = (tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw*)p;
	nimGCvisit((void*)(*a).req1.client, op);
	nimGCvisit((void*)(*a).req1.headers, op);
	nimGCvisit((void*)(*a).req1.protocol.Field0, op);
	nimGCvisit((void*)(*a).req1.url.scheme, op);
	nimGCvisit((void*)(*a).req1.url.username, op);
	nimGCvisit((void*)(*a).req1.url.password, op);
	nimGCvisit((void*)(*a).req1.url.hostname, op);
	nimGCvisit((void*)(*a).req1.url.port, op);
	nimGCvisit((void*)(*a).req1.url.path, op);
	nimGCvisit((void*)(*a).req1.url.query, op);
	nimGCvisit((void*)(*a).req1.url.anchor, op);
	nimGCvisit((void*)(*a).req1.hostname, op);
	nimGCvisit((void*)(*a).req1.body, op);
	nimGCvisit((void*)(*a).retFuture2, op);
	nimGCvisit((void*)(*a).nameIterVar3.ClE_0, op);
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_INo2UmKIotXHE9b9b2NJGwbg)(void* p, NI op) {
	tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww* a;
	a = (tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww*)p;
	nimGCvisit((void*)(*a).future1, op);
	nimGCvisit((void*)(*a).colonup_, op);
}

N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, cbIter_TqaV9a1VSlZPZWTetcSzfdw)(void* ClE_0) {
	tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* result;
	tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww* colonenvP_;
	nimfr_("cbIter", "asyncmacro.nim");
{	result = (tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*)0;
	colonenvP_ = (tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww*) ClE_0;
	switch ((*colonenvP_).colonstate_) {
	case -1: goto BeforeRet_;
	case 0: goto STATE0;
	case 1: goto STATE1;
	}
	STATE0: ;
	nimln_(6, "hello_server.nim");
	asgnRef((void**) (&(*colonenvP_).future1), respond_F4lmxjjqUOo55CrHJJWOJw((&(*(*colonenvP_).colonup_).req1), ((NI) 200), ((NimStringDesc*) &TM_sJmeuNYREbk30tBbLmMX4g_6), NIM_NIL));
	(*colonenvP_).colonstate_ = ((NI) 1);
	nimln_(132, "asyncmacro.nim");
	result = &(*colonenvP_).future1->Sup;
	goto BeforeRet_;
	STATE1: ;
	read_EYgDXwwneJeAEUfXLUHmhg((*colonenvP_).future1);
	nimln_(343, "asyncmacro.nim");
	complete_mvHczm6KlNpTkVsXGCEbgg((*(*colonenvP_).colonup_).retFuture2);
	(*colonenvP_).colonstate_ = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(NIM_BOOL, finished_lnX3UZC8cmCUb7BzjNqokQasyncdispatch)(tyProc_3cmVDZYspcmD9a16VGUFJoA x) {
	NIM_BOOL result;
	nimfr_("finished", "system.nim");
	result = (NIM_BOOL)0;
	nimln_(3399, "system.nim");
	      result = ((NI*) x.ClE_0)[1] < 0;
      
	popFrame();
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "system.nim");
	result = (Exception*)0;
	nimln_(3350, "system.nim");
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), (*currException_9bVPeDJlYTi9bQApZpfH8wjg).up);
}

N_LIB_PRIVATE N_CLOSURE(void, cb_continue_nWTMpJKJbxXeWUVE9bCQj9aA)(void* ClE_0) {
	tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw* colonenvP_;
	TSafePoint TM_sJmeuNYREbk30tBbLmMX4g_7;
	nimfr_("cb_continue", "asyncmacro.nim");
	colonenvP_ = (tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw*) ClE_0;
	nimln_(32, "asyncmacro.nim");
	pushSafePoint(&TM_sJmeuNYREbk30tBbLmMX4g_7);
	TM_sJmeuNYREbk30tBbLmMX4g_7.status = _setjmp(TM_sJmeuNYREbk30tBbLmMX4g_7.context);
	if (TM_sJmeuNYREbk30tBbLmMX4g_7.status == 0) {
		nimln_(33, "asyncmacro.nim");
		{
			NIM_BOOL T4_;
			tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* volatile next;
			T4_ = (NIM_BOOL)0;
			T4_ = finished_lnX3UZC8cmCUb7BzjNqokQasyncdispatch((*colonenvP_).nameIterVar3);
			if (!!(T4_)) goto LA5_;
			nimln_(34, "asyncmacro.nim");
			next = (*colonenvP_).nameIterVar3.ClP_0((*colonenvP_).nameIterVar3.ClE_0);
			{
				nimln_(36, "asyncmacro.nim");
				while (1) {
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = !((next == 0));
					if (!(T9_)) goto LA10_;
					T9_ = finished_ZDnEFECD9b9aKFsuVLxFyzkA_2(next);
					LA10_: ;
					if (!T9_) goto LA8;
					nimln_(37, "asyncmacro.nim");
					next = (*colonenvP_).nameIterVar3.ClP_0((*colonenvP_).nameIterVar3.ClE_0);
					nimln_(38, "asyncmacro.nim");
					{
						NIM_BOOL T13_;
						T13_ = (NIM_BOOL)0;
						T13_ = finished_lnX3UZC8cmCUb7BzjNqokQasyncdispatch((*colonenvP_).nameIterVar3);
						if (!T13_) goto LA14_;
						nimln_(39, "asyncmacro.nim");
						goto LA7;
					}
					LA14_: ;
				} LA8: ;
			} LA7: ;
			nimln_(41, "asyncmacro.nim");
			{
				if (!(next == NIM_NIL)) goto LA18_;
				nimln_(42, "asyncmacro.nim");
				{
					NIM_BOOL T22_;
					NimStringDesc* msg;
					tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA* volatile e;
					nimln_(401, "asyncmacro.nim");
					T22_ = (NIM_BOOL)0;
					T22_ = finished_jn4eVK3zFIl4kShRnlTsCg((*colonenvP_).retFuture2);
					if (!!(T22_)) goto LA23_;
					nimln_(43, "asyncmacro.nim");
					msg = copyString(((NimStringDesc*) &TM_sJmeuNYREbk30tBbLmMX4g_10));
					e = (tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA*)0;
					nimln_(2811, "system.nim");
					e = (tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA*) newObj((&NTI_TmgWlPUbRr7iGD2UE1cu6A_), sizeof(tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA));
					(*e).Sup.Sup.m_type = (&NTI_8FC9arcap3s5ZtfMs75krtA_);
					nimln_(45, "asyncmacro.nim");
					asgnRefNoCycle((void**) (&(*e).Sup.message), nsuFormatSingleElem(msg, ((NimStringDesc*) &TM_sJmeuNYREbk30tBbLmMX4g_4)));
					nimln_(2806, "system.nim");
					asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
					nimln_(45, "asyncmacro.nim");
					raiseException((Exception*)e, "AssertionError");
				}
				LA23_: ;
			}
			goto LA16_;
			LA18_: ;
			{
				tyProc_IIomJ6ptE6vfJ5zRbATgkQ T26_;
				nimln_(49, "asyncmacro.nim");
				memset((void*)(&T26_), 0, sizeof(T26_));
				T26_.ClP_0 = cb_continue_nWTMpJKJbxXeWUVE9bCQj9aA; T26_.ClE_0 = colonenvP_;
				callbackeq__9c5z7ouO5bUylgKxaZoIuVg_2(next, T26_);
			}
			LA16_: ;
		}
		LA5_: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
		{
			TM_sJmeuNYREbk30tBbLmMX4g_7.status = 0;
			nimln_(54, "asyncmacro.nim");
			{
				NIM_BOOL T31_;
				nimln_(401, "asyncmacro.nim");
				T31_ = (NIM_BOOL)0;
				T31_ = finished_jn4eVK3zFIl4kShRnlTsCg((*colonenvP_).retFuture2);
				if (!T31_) goto LA32_;
				nimln_(57, "asyncmacro.nim");
				reraiseException();
			}
			goto LA29_;
			LA32_: ;
			{
				Exception* T35_;
				nimln_(401, "asyncmacro.nim");
				nimln_(59, "asyncmacro.nim");
				T35_ = (Exception*)0;
				T35_ = getCurrentException();
				fail_8buDkIPh9aRg7WBcB15eisA((*colonenvP_).retFuture2, T35_);
			}
			LA29_: ;
			popCurrentException();
		}
	}
	if (TM_sJmeuNYREbk30tBbLmMX4g_7.status != 0) reraiseException();
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, cb_7z9cfXflyq3fFV9aWo0NvH9cg)(tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* req) {
	tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* result;
	tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw* colonenv_;
	tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww* colonenv__2;
	tyProc_3cmVDZYspcmD9a16VGUFJoA T1_;
	tyProc_IIomJ6ptE6vfJ5zRbATgkQ T2_;
	nimfr_("cb", "hello_server.nim");
{	result = (tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*)0;
	colonenv_ = (tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw*)0;
	nimln_(5, "hello_server.nim");
	colonenv_ = (tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw*) newObj((&NTI_B4LxXdb5z5tVUEzMUA22Tg_), sizeof(tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw));
	(*colonenv_).Sup.m_type = (&NTI_Wqr0V9aQLrJgTvyTpMjKO9bw_);
	genericAssign((void*)(&(*colonenv_).req1), (void*)req, (&NTI_1Wfxxtqzahm0R6lueM9aQmQ_));
	asgnRef((void**) (&(*colonenv_).retFuture2), newFuture_cw7L2Vu5pdfKvHqESZUwnA(((NimStringDesc*) &TM_sJmeuNYREbk30tBbLmMX4g_4)));
	nimln_(29, "asyncmacro.nim");
	colonenv__2 = (tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww*)0;
	nimln_(401, "asyncmacro.nim");
	colonenv__2 = (tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww*) newObj((&NTI_INo2UmKIotXHE9b9b2NJGwbg_), sizeof(tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww));
	(*colonenv__2).Sup.m_type = (&NTI_FC9cRk6qkw2JfD0NYbUD0ww_);
	nimln_(5, "hello_server.nim");
	asgnRef((void**) (&(*colonenv__2).colonup_), colonenv_);
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.ClP_0 = cbIter_TqaV9a1VSlZPZWTetcSzfdw; T1_.ClE_0 = colonenv__2;
	asgnRef((void**) (&(*colonenv_).nameIterVar3.ClE_0), T1_.ClE_0);
	(*colonenv_).nameIterVar3.ClP_0 = T1_.ClP_0;
	nimln_(401, "asyncmacro.nim");
	memset((void*)(&T2_), 0, sizeof(T2_));
	T2_.ClP_0 = cb_continue_nWTMpJKJbxXeWUVE9bCQj9aA; T2_.ClE_0 = colonenv_;
	T2_.ClE_0? T2_.ClP_0(T2_.ClE_0):((TM_sJmeuNYREbk30tBbLmMX4g_11)(T2_.ClP_0))();
	nimln_(6, "hello_server.nim");
	nimln_(401, "asyncmacro.nim");
	result = (*colonenv_).retFuture2;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_heapqueueDatInit000();
	stdlib_listsDatInit000();
	stdlib_typetraitsDatInit000();
	stdlib_optionsDatInit000();
	stdlib_dequesDatInit000();
	stdlib_cstrutilsDatInit000();
	stdlib_asyncfuturesDatInit000();
	stdlib_asyncstreamsDatInit000();
	stdlib_nativesocketsDatInit000();
	stdlib_setsDatInit000();
	stdlib_netDatInit000();
	stdlib_kqueueDatInit000();
	stdlib_selectorsDatInit000();
	stdlib_macrosDatInit000();
	stdlib_asyncdispatchDatInit000();
	stdlib_asyncnetDatInit000();
	stdlib_uriDatInit000();
	stdlib_httpcoreDatInit000();
	stdlib_asynchttpserverDatInit000();
	hello_serverDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_heapqueueInit000();
	stdlib_listsInit000();
	stdlib_typetraitsInit000();
	stdlib_optionsInit000();
	stdlib_dequesInit000();
	stdlib_cstrutilsInit000();
	stdlib_asyncfuturesInit000();
	stdlib_asyncstreamsInit000();
	stdlib_nativesocketsInit000();
	stdlib_setsInit000();
	stdlib_netInit000();
	stdlib_kqueueInit000();
	stdlib_selectorsInit000();
	stdlib_macrosInit000();
	stdlib_asyncdispatchInit000();
	stdlib_asyncnetInit000();
	stdlib_uriInit000();
	stdlib_httpcoreInit000();
	stdlib_asynchttpserverInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyProc_9cYHoVsKEcSHuZkNJna2Tvg T1_;
	tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* T2_;
	nimfr_("hello_server", "hello_server.nim");
nimRegisterGlobalMarker(TM_sJmeuNYREbk30tBbLmMX4g_2);
	nimln_(3, "hello_server.nim");
	asgnRefNoCycle((void**) (&server_6AeqIvTsg3xq4ajrBvLQAQ), newAsyncHttpServer_8E3hcKWR9bMseKjk69aa6Aqw(NIM_TRUE, NIM_FALSE, ((NI) 8388608)));
	nimln_(8, "hello_server.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.ClP_0 = ((TM_sJmeuNYREbk30tBbLmMX4g_12) (cb_7z9cfXflyq3fFV9aWo0NvH9cg)); T1_.ClE_0 = NIM_NIL;
	T2_ = (tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*)0;
	T2_ = serve_4qUYuAmkUBQy1ChRq42g5Q(server_6AeqIvTsg3xq4ajrBvLQAQ, ((NU16) 8080), T1_, ((NimStringDesc*) &TM_sJmeuNYREbk30tBbLmMX4g_13));
	waitFor_VIKMhEBTNLqEA2ZGnacjrw(T2_);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, hello_serverDatInit000)(void) {
static TNimNode* TM_sJmeuNYREbk30tBbLmMX4g_3[4];
static TNimNode* TM_sJmeuNYREbk30tBbLmMX4g_5[3];
static TNimNode TM_sJmeuNYREbk30tBbLmMX4g_0[9];
NTI_Wqr0V9aQLrJgTvyTpMjKO9bw_.size = sizeof(tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw);
NTI_Wqr0V9aQLrJgTvyTpMjKO9bw_.kind = 17;
NTI_Wqr0V9aQLrJgTvyTpMjKO9bw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_sJmeuNYREbk30tBbLmMX4g_3[0] = &TM_sJmeuNYREbk30tBbLmMX4g_0[1];
TM_sJmeuNYREbk30tBbLmMX4g_0[1].kind = 1;
TM_sJmeuNYREbk30tBbLmMX4g_0[1].offset = offsetof(tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw, colonstate_);
TM_sJmeuNYREbk30tBbLmMX4g_0[1].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_sJmeuNYREbk30tBbLmMX4g_0[1].name = ":state";
TM_sJmeuNYREbk30tBbLmMX4g_3[1] = &TM_sJmeuNYREbk30tBbLmMX4g_0[2];
TM_sJmeuNYREbk30tBbLmMX4g_0[2].kind = 1;
TM_sJmeuNYREbk30tBbLmMX4g_0[2].offset = offsetof(tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw, req1);
TM_sJmeuNYREbk30tBbLmMX4g_0[2].typ = (&NTI_1Wfxxtqzahm0R6lueM9aQmQ_);
TM_sJmeuNYREbk30tBbLmMX4g_0[2].name = "req1";
TM_sJmeuNYREbk30tBbLmMX4g_3[2] = &TM_sJmeuNYREbk30tBbLmMX4g_0[3];
TM_sJmeuNYREbk30tBbLmMX4g_0[3].kind = 1;
TM_sJmeuNYREbk30tBbLmMX4g_0[3].offset = offsetof(tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw, retFuture2);
TM_sJmeuNYREbk30tBbLmMX4g_0[3].typ = (&NTI_zXD0JrbeCNyAaW4E6fB9aqg_);
TM_sJmeuNYREbk30tBbLmMX4g_0[3].name = "retFuture2";
TM_sJmeuNYREbk30tBbLmMX4g_3[3] = &TM_sJmeuNYREbk30tBbLmMX4g_0[4];
TM_sJmeuNYREbk30tBbLmMX4g_0[4].kind = 1;
TM_sJmeuNYREbk30tBbLmMX4g_0[4].offset = offsetof(tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw, nameIterVar3);
TM_sJmeuNYREbk30tBbLmMX4g_0[4].typ = (&NTI_3cmVDZYspcmD9a16VGUFJoA_);
TM_sJmeuNYREbk30tBbLmMX4g_0[4].name = "nameIterVar3";
TM_sJmeuNYREbk30tBbLmMX4g_0[0].len = 4; TM_sJmeuNYREbk30tBbLmMX4g_0[0].kind = 2; TM_sJmeuNYREbk30tBbLmMX4g_0[0].sons = &TM_sJmeuNYREbk30tBbLmMX4g_3[0];
NTI_Wqr0V9aQLrJgTvyTpMjKO9bw_.node = &TM_sJmeuNYREbk30tBbLmMX4g_0[0];
NTI_B4LxXdb5z5tVUEzMUA22Tg_.size = sizeof(tyObject_Env_hello_serverdotnim__Wqr0V9aQLrJgTvyTpMjKO9bw*);
NTI_B4LxXdb5z5tVUEzMUA22Tg_.kind = 22;
NTI_B4LxXdb5z5tVUEzMUA22Tg_.base = (&NTI_Wqr0V9aQLrJgTvyTpMjKO9bw_);
NTI_B4LxXdb5z5tVUEzMUA22Tg_.marker = Marker_tyRef_B4LxXdb5z5tVUEzMUA22Tg;
NTI_FC9cRk6qkw2JfD0NYbUD0ww_.size = sizeof(tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww);
NTI_FC9cRk6qkw2JfD0NYbUD0ww_.kind = 17;
NTI_FC9cRk6qkw2JfD0NYbUD0ww_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_sJmeuNYREbk30tBbLmMX4g_5[0] = &TM_sJmeuNYREbk30tBbLmMX4g_0[6];
TM_sJmeuNYREbk30tBbLmMX4g_0[6].kind = 1;
TM_sJmeuNYREbk30tBbLmMX4g_0[6].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww, colonstate_);
TM_sJmeuNYREbk30tBbLmMX4g_0[6].typ = (&NTI_Mpt8aZ13tT2AYV71yyfHcA_);
TM_sJmeuNYREbk30tBbLmMX4g_0[6].name = ":state";
TM_sJmeuNYREbk30tBbLmMX4g_5[1] = &TM_sJmeuNYREbk30tBbLmMX4g_0[7];
TM_sJmeuNYREbk30tBbLmMX4g_0[7].kind = 1;
TM_sJmeuNYREbk30tBbLmMX4g_0[7].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww, future1);
TM_sJmeuNYREbk30tBbLmMX4g_0[7].typ = (&NTI_zXD0JrbeCNyAaW4E6fB9aqg_);
TM_sJmeuNYREbk30tBbLmMX4g_0[7].name = "future1";
TM_sJmeuNYREbk30tBbLmMX4g_5[2] = &TM_sJmeuNYREbk30tBbLmMX4g_0[8];
TM_sJmeuNYREbk30tBbLmMX4g_0[8].kind = 1;
TM_sJmeuNYREbk30tBbLmMX4g_0[8].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww, colonup_);
TM_sJmeuNYREbk30tBbLmMX4g_0[8].typ = (&NTI_B4LxXdb5z5tVUEzMUA22Tg_);
TM_sJmeuNYREbk30tBbLmMX4g_0[8].name = ":up";
TM_sJmeuNYREbk30tBbLmMX4g_0[5].len = 3; TM_sJmeuNYREbk30tBbLmMX4g_0[5].kind = 2; TM_sJmeuNYREbk30tBbLmMX4g_0[5].sons = &TM_sJmeuNYREbk30tBbLmMX4g_5[0];
NTI_FC9cRk6qkw2JfD0NYbUD0ww_.node = &TM_sJmeuNYREbk30tBbLmMX4g_0[5];
NTI_INo2UmKIotXHE9b9b2NJGwbg_.size = sizeof(tyObject_Env_libslashpureslashasyncmacrodotnim__FC9cRk6qkw2JfD0NYbUD0ww*);
NTI_INo2UmKIotXHE9b9b2NJGwbg_.kind = 22;
NTI_INo2UmKIotXHE9b9b2NJGwbg_.base = (&NTI_FC9cRk6qkw2JfD0NYbUD0ww_);
NTI_INo2UmKIotXHE9b9b2NJGwbg_.marker = Marker_tyRef_INo2UmKIotXHE9b9b2NJGwbg;
}

