/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.18.0_1/nim/lib -o /Users/faysalahmed/Documents/projects/nim_projects/hello_nim/nimcache/stdlib_tables.o /Users/faysalahmed/Documents/projects/nim_projects/hello_nim/nimcache/stdlib_tables.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA tyObject_Table_LLQadDAXEvd71UDdEc3lDA;
typedef struct tySequence_JiteSJxrvz63iP2o9bcn2Sg tySequence_JiteSJxrvz63iP2o9bcn2Sg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ tyTuple_g1w83cyyBYiVU9c8WEJWnjQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyTuple_wOvXi5VibnCNgN9buQRQD4A tyTuple_wOvXi5VibnCNgN9buQRQD4A;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA {
tySequence_JiteSJxrvz63iP2o9bcn2Sg* data;
NI counter;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ {
NI Field0;
NimStringDesc* Field1;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field2;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyTuple_wOvXi5VibnCNgN9buQRQD4A {
NimStringDesc* Field0;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field1;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_JiteSJxrvz63iP2o9bcn2Sg {
  TGenericSeq Sup;
  tyTuple_g1w83cyyBYiVU9c8WEJWnjQ data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isEmpty_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, rightSize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA)(NI x);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_JiteSJxrvz63iP2o9bcn2Sg)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_Exo1CrLCLUIZQ4IUZ9aXEGg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, initTable_11SA0A9aqibwRCaMRv3dYJg)(NI initialSize, tyObject_Table_LLQadDAXEvd71UDdEc3lDA* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg)(NI x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, toTable_KvTZkBNepHskThOGwbKNQw)(tyTuple_wOvXi5VibnCNgN9buQRQD4A* pairs, NI pairsLen_0, tyObject_Table_LLQadDAXEvd71UDdEc3lDA* Result);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__un8Mk4BNkyXrzCk9aVyJLyg)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* val);
static N_INLINE(NI, rawGet_IKEP9cnFCFaJ7ddTfNBNwiAtables)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_4fNF0muhv9bnh9cyCNXdBTGw)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_b307VXuGrKMvRrWyJu8KAA)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, tySequence_JiteSJxrvz63iP2o9bcn2Sg** data, NimStringDesc* key, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* val, NI hc, NI h);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, rawGetKnownHC_RKwyKXZlTvFd0VZfVx9bcgQtables)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA t, NimStringDesc* key, NI hc);
N_LIB_PRIVATE N_NIMCALL(NI, len_gPutmFMjF2dpNdfOqcokuQ)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_KHwyPEV6PV8Q9aS88ENydhw)(NimStringDesc** s, NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_iFcuOX1Mlpkt1duTcalbSA)(NimStringDesc** s, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* x);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ**, X5BX5D__IuN3JD9aQgZX7ND9cYyXSo8g)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_pcmEVCyAwAm4n6uMb9bd7mQ)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, del_qvMk5umInCk9bpiZXt9aZZvg)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_LLQadDAXEvd71UDdEc3lDA_;
TNimType NTI_g1w83cyyBYiVU9c8WEJWnjQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
TNimType NTI_JiteSJxrvz63iP2o9bcn2Sg_;
TNimType NTI_Exo1CrLCLUIZQ4IUZ9aXEGg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_axqhRnwd09cVJkRcojfw6mA_;
extern TNimType NTI_ifYAhUumNzWR9c9cN9amyJLtg_;
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_2, "\012counter < length ", 18);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_12, "isPowerOfTwo(initialSize) ", 26);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_20, "{:}", 3);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_21, "{", 1);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_22, ", ", 2);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_23, ": ", 2);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_25, "}", 1);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_27, "key not found: ", 15);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isEmpty_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isEmpty", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(15, "tableimpl.nim");
	result = (hcode == ((NI) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(398, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL T5_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_3;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_4;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_5;
	nimfr_("mustRehash", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(24, "tableimpl.nim");
	{
		if (!!((counter < length))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_2));
	}
	LA3_: ;
	nimln_(25, "tableimpl.nim");
	T5_ = (NIM_BOOL)0;
	TM_4SoG2KRQy3oMm9aUzSLtGrA_3 = mulInt(length, ((NI) 2));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_4 = mulInt(counter, ((NI) 3));
	T5_ = ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_3) < (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_4));
	if (T5_) goto LA6_;
	TM_4SoG2KRQy3oMm9aUzSLtGrA_5 = subInt(length, counter);
	T5_ = ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_5) < ((NI) 4));
	LA6_: ;
	result = T5_;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_6;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_6 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_6) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rightSize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count) {
	NI result;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_7;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_8;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_9;
	nimfr_("rightSize", "tables.nim");
	result = (NI)0;
	nimln_(136, "tables.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_7 = mulInt(((NI) (count)), ((NI) 3));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_8 = divInt((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_7), ((NI) 2));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_9 = addInt((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_8), ((NI) 4));
	result = nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_9));
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_JiteSJxrvz63iP2o9bcn2Sg)(void* p, NI op) {
	tySequence_JiteSJxrvz63iP2o9bcn2Sg* a;
	NI T1_;
	a = (tySequence_JiteSJxrvz63iP2o9bcn2Sg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	nimGCvisit((void*)a->data[T1_].Field2, op);
	}
}
static N_NIMCALL(void, Marker_tyRef_Exo1CrLCLUIZQ4IUZ9aXEGg)(void* p, NI op) {
	tyObject_Table_LLQadDAXEvd71UDdEc3lDA* a;
	a = (tyObject_Table_LLQadDAXEvd71UDdEc3lDA*)p;
	nimGCvisit((void*)(*a).data, op);
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, initTable_11SA0A9aqibwRCaMRv3dYJg)(NI initialSize, tyObject_Table_LLQadDAXEvd71UDdEc3lDA* Result) {
	nimfr_("initTable", "tables.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_LLQadDAXEvd71UDdEc3lDA_));
	nimln_(324, "tables.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialSize);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_12));
	}
	LA4_: ;
	nimln_(325, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln_(326, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_JiteSJxrvz63iP2o9bcn2Sg*) newSeq((&NTI_JiteSJxrvz63iP2o9bcn2Sg_), ((NI)chckRange(initialSize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Table_LLQadDAXEvd71UDdEc3lDA*, newTable_CI6CAcgU9cmDZWyfVHj8z4g)(NI initialSize) {
	tyObject_Table_LLQadDAXEvd71UDdEc3lDA* result;
	nimfr_("newTable", "tables.nim");
	result = (tyObject_Table_LLQadDAXEvd71UDdEc3lDA*)0;
	nimln_(449, "tables.nim");
	result = (tyObject_Table_LLQadDAXEvd71UDdEc3lDA*) newObj((&NTI_Exo1CrLCLUIZQ4IUZ9aXEGg_), sizeof(tyObject_Table_LLQadDAXEvd71UDdEc3lDA));
	nimln_(450, "tables.nim");
	initTable_11SA0A9aqibwRCaMRv3dYJg(initialSize, (&(*result)));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_IKEP9cnFCFaJ7ddTfNBNwiAtables)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_13;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_13 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_13);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_b307VXuGrKMvRrWyJu8KAA)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, tySequence_JiteSJxrvz63iP2o9bcn2Sg** data, NimStringDesc* key, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* val, NI hc, NI h) {
	NimStringDesc* T1_;
	nimfr_("rawInsert", "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(64, "tableimpl.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (T1_) nimGCunrefNoCycle(T1_);
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(65, "tableimpl.nim");
	genericSeqAssign((&(*data)->data[h].Field2), val, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(66, "tableimpl.nim");
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_4fNF0muhv9bnh9cyCNXdBTGw)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t) {
	tySequence_JiteSJxrvz63iP2o9bcn2Sg* n;
	NI T1_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_14;
	tySequence_JiteSJxrvz63iP2o9bcn2Sg* T2_;
	nimfr_("enlarge", "tables.nim");
	n = (tySequence_JiteSJxrvz63iP2o9bcn2Sg*)0;
	nimln_(286, "tables.nim");
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	TM_4SoG2KRQy3oMm9aUzSLtGrA_14 = mulInt(T1_, ((NI) 2));
	n = (tySequence_JiteSJxrvz63iP2o9bcn2Sg*) newSeq((&NTI_JiteSJxrvz63iP2o9bcn2Sg_), ((NI)chckRange((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_14), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(287, "tables.nim");
	T2_ = (tySequence_JiteSJxrvz63iP2o9bcn2Sg*)0;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(288, "tables.nim");
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		nimln_(2032, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2033, "system.nim");
			while (1) {
				NI eh;
				NI TM_4SoG2KRQy3oMm9aUzSLtGrA_15;
				if (!(res <= colontmp_)) goto LA6;
				nimln_(2034, "system.nim");
				i = res;
				nimln_(289, "tables.nim");
				if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
				eh = n->data[i].Field0;
				nimln_(290, "tables.nim");
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(eh);
					if (!T9_) goto LA10_;
					nimln_(291, "tables.nim");
					nimln_(116, "tables.nim");
					T12_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
					j = (NI)(eh & T12_);
					{
						nimln_(292, "tables.nim");
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							if ((NU)(j) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							nimln_(293, "tables.nim");
							nimln_(116, "tables.nim");
							T16_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
							j = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(j, T16_);
						} LA14: ;
					}
					nimln_(294, "tables.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					rawInsert_b307VXuGrKMvRrWyJu8KAA(t, (&(*t).data), n->data[i].Field1, n->data[i].Field2, eh, j);
				}
				LA10_: ;
				nimln_(2035, "system.nim");
				TM_4SoG2KRQy3oMm9aUzSLtGrA_15 = addInt(res, ((NI) 1));
				res = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_15);
			} LA6: ;
		}
	}
	popFrame();
}

static N_INLINE(NI, rawGetKnownHC_RKwyKXZlTvFd0VZfVx9bcgQtables)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_16;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_16 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_16);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__un8Mk4BNkyXrzCk9aVyJLyg)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* val) {
	NI hc;
	NI index;
	nimfr_("[]=", "tables.nim");
	hc = (NI)0;
	nimln_(98, "tableimpl.nim");
	index = rawGet_IKEP9cnFCFaJ7ddTfNBNwiAtables((*t), key, (&hc));
	nimln_(307, "tables.nim");
	{
		nimln_(99, "tableimpl.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		genericSeqAssign((&(*t).data->data[index].Field2), val, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_17;
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_18;
		nimln_(89, "tableimpl.nim");
		{
			NI T8_;
			NIM_BOOL T9_;
			nimln_(117, "tables.nim");
			T8_ = ((*t).data ? (*t).data->Sup.len : 0);
			T9_ = (NIM_BOOL)0;
			T9_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T8_, (*t).counter);
			if (!T9_) goto LA10_;
			nimln_(90, "tableimpl.nim");
			enlarge_4fNF0muhv9bnh9cyCNXdBTGw(t);
			nimln_(91, "tableimpl.nim");
			index = rawGetKnownHC_RKwyKXZlTvFd0VZfVx9bcgQtables((*t), key, hc);
		}
		LA10_: ;
		nimln_(92, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_17 = subInt(((NI) -1), index);
		index = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_17);
		nimln_(93, "tableimpl.nim");
		rawInsert_b307VXuGrKMvRrWyJu8KAA(t, (&(*t).data), key, val, hc, index);
		nimln_(94, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_18 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_18);
	}
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, toTable_KvTZkBNepHskThOGwbKNQw)(tyTuple_wOvXi5VibnCNgN9buQRQD4A* pairs, NI pairsLen_0, tyObject_Table_LLQadDAXEvd71UDdEc3lDA* Result) {
	NI T1_;
	nimfr_("toTable", "tables.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_LLQadDAXEvd71UDdEc3lDA_));
	nimln_(331, "tables.nim");
	T1_ = (NI)0;
	T1_ = rightSize_l3wfAVpWNBWtzL8kQfvMMAtables(((NI)chckRange(pairsLen_0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	initTable_11SA0A9aqibwRCaMRv3dYJg(T1_, Result);
	{
		NimStringDesc* key;
		tySequence_sM4lkSb7zS6F7OVMvW9cffQ* val;
		NI i;
		key = (NimStringDesc*)0;
		val = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		nimln_(2185, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_4SoG2KRQy3oMm9aUzSLtGrA_19;
				if (!(i < pairsLen_0)) goto LA4;
				nimln_(2187, "system.nim");
				if ((NU)(i) >= (NU)(pairsLen_0)) raiseIndexError();
				key = pairs[i].Field0;
				if ((NU)(i) >= (NU)(pairsLen_0)) raiseIndexError();
				val = pairs[i].Field1;
				nimln_(332, "tables.nim");
				X5BX5Deq__un8Mk4BNkyXrzCk9aVyJLyg(Result, key, val);
				nimln_(2188, "system.nim");
				TM_4SoG2KRQy3oMm9aUzSLtGrA_19 = addInt(i, ((NI) 1));
				i = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_19);
			} LA4: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Table_LLQadDAXEvd71UDdEc3lDA*, newTable_vwPfOZ6WCX1qHilQ0EWk9bQ)(tyTuple_wOvXi5VibnCNgN9buQRQD4A* pairs, NI pairsLen_0) {
	tyObject_Table_LLQadDAXEvd71UDdEc3lDA* result;
	nimfr_("newTable", "tables.nim");
	result = (tyObject_Table_LLQadDAXEvd71UDdEc3lDA*)0;
	nimln_(454, "tables.nim");
	result = (tyObject_Table_LLQadDAXEvd71UDdEc3lDA*) newObj((&NTI_Exo1CrLCLUIZQ4IUZ9aXEGg_), sizeof(tyObject_Table_LLQadDAXEvd71UDdEc3lDA));
	nimln_(455, "tables.nim");
	toTable_KvTZkBNepHskThOGwbKNQw(pairs, pairsLen_0, (&(*result)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, len_gPutmFMjF2dpNdfOqcokuQ)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t) {
	NI result;
	nimfr_("len", "tables.nim");
	result = (NI)0;
	nimln_(316, "tables.nim");
	result = (*t).counter;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__gqdUdur9ancraXE7H0hbi5w)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t) {
	NimStringDesc* result;
	nimfr_("$", "tables.nim");
	result = (NimStringDesc*)0;
	nimln_(459, "tables.nim");
	{
		NI T3_;
		nimln_(335, "tables.nim");
		T3_ = (NI)0;
		T3_ = len_gPutmFMjF2dpNdfOqcokuQ(t);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(336, "tables.nim");
		result = copyString(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_20));
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(338, "tables.nim");
		result = copyString(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_21));
		{
			NimStringDesc* key;
			tySequence_sM4lkSb7zS6F7OVMvW9cffQ* val;
			key = (NimStringDesc*)0;
			val = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
			{
				NI h;
				NI colontmp_;
				NI T9_;
				NI res;
				h = (NI)0;
				colontmp_ = (NI)0;
				nimln_(377, "tables.nim");
				T9_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
				colontmp_ = T9_;
				nimln_(2045, "system.nim");
				res = ((NI) 0);
				{
					nimln_(2046, "system.nim");
					while (1) {
						NI TM_4SoG2KRQy3oMm9aUzSLtGrA_24;
						if (!(res <= colontmp_)) goto LA11;
						nimln_(2047, "system.nim");
						h = res;
						nimln_(378, "tables.nim");
						{
							NIM_BOOL T14_;
							if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							T14_ = (NIM_BOOL)0;
							T14_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[h].Field0);
							if (!T14_) goto LA15_;
							if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							key = (*t).data->data[h].Field1;
							if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							val = (*t).data->data[h].Field2;
							nimln_(340, "tables.nim");
							{
								if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA19_;
								result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_22));
							}
							LA19_: ;
							nimln_(341, "tables.nim");
							addQuoted_KHwyPEV6PV8Q9aS88ENydhw((&result), key);
							nimln_(342, "tables.nim");
							result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_23));
							nimln_(343, "tables.nim");
							addQuoted_iFcuOX1Mlpkt1duTcalbSA((&result), val);
						}
						LA15_: ;
						nimln_(2048, "system.nim");
						TM_4SoG2KRQy3oMm9aUzSLtGrA_24 = addInt(res, ((NI) 1));
						res = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_24);
					} LA11: ;
				}
			}
		}
		nimln_(344, "tables.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_25));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, clear_axjU83goYo2deNG5N5zCTA)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t) {
	nimfr_("clear", "tables.nim");
	{
		NI i;
		NI colontmp_;
		NI T2_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(152, "tableimpl.nim");
		T2_ = ((*t).data ? (*t).data->Sup.len : 0);
		colontmp_ = T2_;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NimStringDesc* v;
				NimStringDesc* T5_;
				tySequence_sM4lkSb7zS6F7OVMvW9cffQ* v_2;
				NI TM_4SoG2KRQy3oMm9aUzSLtGrA_26;
				if (!(i_2 < colontmp_)) goto LA4;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				nimln_(154, "tableimpl.nim");
				(*t).data->data[i].Field0 = ((NI) 0);
				if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				nimln_(155, "tableimpl.nim");
				v = (NimStringDesc*)0;
				T5_ = (NimStringDesc*)0;
				T5_ = (*t).data->data[i].Field1; (*t).data->data[i].Field1 = copyStringRC1(v);
				if (T5_) nimGCunrefNoCycle(T5_);
				if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				nimln_(156, "tableimpl.nim");
				v_2 = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
				genericSeqAssign((&(*t).data->data[i].Field2), v_2, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
				nimln_(3522, "system.nim");
				TM_4SoG2KRQy3oMm9aUzSLtGrA_26 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_26);
			} LA4: ;
		}
	}
	nimln_(157, "tableimpl.nim");
	(*t).counter = ((NI) 0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ**, X5BX5D__IuN3JD9aQgZX7ND9cYyXSo8g)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ** result;
	NI hc;
	NI index;
	nimfr_("[]", "tables.nim");
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ**)0;
	hc = (NI)0;
	nimln_(147, "tables.nim");
	index = rawGet_IKEP9cnFCFaJ7ddTfNBNwiAtables((*t), key, (&hc));
	nimln_(170, "tables.nim");
	{
		nimln_(148, "tables.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = (&(*t).data->data[index].Field2);
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		nimln_(151, "tables.nim");
		T6_ = (NimStringDesc*)0;
		nimln_(170, "tables.nim");
		T6_ = rawNewString(key->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_27));
appendString(T6_, key);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(151, "tables.nim");
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ**, X5BX5D__Q3d9cok5U8i0JCsF7VnnIJw)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ** result;
	nimfr_("[]", "tables.nim");
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ**)0;
	nimln_(405, "tables.nim");
	result = X5BX5D__IuN3JD9aQgZX7ND9cYyXSo8g(t, key);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__Hk6a82dIBZqReb79aiZ9czeQ)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* val) {
	nimfr_("[]=", "tables.nim");
	nimln_(430, "tables.nim");
	X5BX5Deq__un8Mk4BNkyXrzCk9aVyJLyg(t, key, val);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_pcmEVCyAwAm4n6uMb9bd7mQ)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA t, NimStringDesc* key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
	nimfr_("hasKey", "tables.nim");
	result = (NIM_BOOL)0;
	hc = (NI)0;
	nimln_(236, "tables.nim");
	T1_ = (NI)0;
	T1_ = rawGet_IKEP9cnFCFaJ7ddTfNBNwiAtables(t, key, (&hc));
	result = (((NI) 0) <= T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_dVPEHWNM9ac65s5ksvHbOhg)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key) {
	NIM_BOOL result;
	nimfr_("hasKey", "tables.nim");
	result = (NIM_BOOL)0;
	nimln_(352, "tables.nim");
	result = hasKey_pcmEVCyAwAm4n6uMb9bd7mQ((*t), key);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, del_qvMk5umInCk9bpiZXt9aZZvg)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key) {
	NI hc;
	NI i;
	NI msk;
	NI T1_;
	nimfr_("del", "tables.nim");
	hc = (NI)0;
	nimln_(148, "tableimpl.nim");
	i = rawGet_IKEP9cnFCFaJ7ddTfNBNwiAtables((*t), key, (&hc));
	nimln_(124, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
	msk = T1_;
	nimln_(270, "tables.nim");
	{
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_28;
		nimln_(125, "tableimpl.nim");
		if (!(((NI) 0) <= i)) goto LA4_;
		nimln_(126, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_28 = subInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_28);
		{
			{
				nimln_(128, "tableimpl.nim");
				while (1) {
					NI j;
					NI r;
					NimStringDesc* v;
					NimStringDesc* T9_;
					tySequence_sM4lkSb7zS6F7OVMvW9cffQ* v_2;
					nimln_(129, "tableimpl.nim");
					j = i;
					nimln_(130, "tableimpl.nim");
					r = j;
					if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					nimln_(131, "tableimpl.nim");
					(*t).data->data[i].Field0 = ((NI) 0);
					if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					nimln_(132, "tableimpl.nim");
					v = (NimStringDesc*)0;
					T9_ = (NimStringDesc*)0;
					T9_ = (*t).data->data[i].Field1; (*t).data->data[i].Field1 = copyStringRC1(v);
					if (T9_) nimGCunrefNoCycle(T9_);
					if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					nimln_(133, "tableimpl.nim");
					v_2 = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
					genericSeqAssign((&(*t).data->data[i].Field2), v_2, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
					{
						nimln_(134, "tableimpl.nim");
						while (1) {
							NI TM_4SoG2KRQy3oMm9aUzSLtGrA_29;
							nimln_(135, "tableimpl.nim");
							nimln_(149, "tableimpl.nim");
							TM_4SoG2KRQy3oMm9aUzSLtGrA_29 = addInt(i, ((NI) 1));
							i = (NI)((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_29) & msk);
							nimln_(136, "tableimpl.nim");
							{
								NIM_BOOL T14_;
								if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
								T14_ = (NIM_BOOL)0;
								T14_ = isEmpty_IxXD1UAPoEehVDW9cv9cRaewtables((*t).data->data[i].Field0);
								if (!T14_) goto LA15_;
								nimln_(137, "tableimpl.nim");
								goto LA6;
							}
							LA15_: ;
							nimln_(138, "tableimpl.nim");
							if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							r = (NI)((*t).data->data[i].Field0 & msk);
							nimln_(139, "tableimpl.nim");
							{
								NIM_BOOL T19_;
								NIM_BOOL T20_;
								NIM_BOOL T21_;
								NIM_BOOL T24_;
								NIM_BOOL T27_;
								T19_ = (NIM_BOOL)0;
								T20_ = (NIM_BOOL)0;
								T21_ = (NIM_BOOL)0;
								T21_ = (r <= i);
								if (!(T21_)) goto LA22_;
								T21_ = (j < r);
								LA22_: ;
								T20_ = T21_;
								if (T20_) goto LA23_;
								T24_ = (NIM_BOOL)0;
								T24_ = (j < r);
								if (!(T24_)) goto LA25_;
								nimln_(149, "tableimpl.nim");
								T24_ = (i < j);
								LA25_: ;
								T20_ = T24_;
								LA23_: ;
								T19_ = T20_;
								if (T19_) goto LA26_;
								nimln_(139, "tableimpl.nim");
								T27_ = (NIM_BOOL)0;
								nimln_(149, "tableimpl.nim");
								T27_ = (i < j);
								if (!(T27_)) goto LA28_;
								nimln_(139, "tableimpl.nim");
								T27_ = (r <= i);
								LA28_: ;
								T19_ = T27_;
								LA26_: ;
								if (!!(T19_)) goto LA29_;
								nimln_(140, "tableimpl.nim");
								goto LA10;
							}
							LA29_: ;
						}
					} LA10: ;
					if ((NU)(j) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					nimln_(144, "tableimpl.nim");
					if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					(*t).data->data[j].Field0 = (*t).data->data[i].Field0;
					asgnRefNoCycle((void**) (&(*t).data->data[j].Field1), (*t).data->data[i].Field1);
					asgnRefNoCycle((void**) (&(*t).data->data[j].Field2), (*t).data->data[i].Field2);
				}
			}
		} LA6: ;
	}
	LA4_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, del_xE9c9cVqHJHvzjbqM89cWGX2w)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key) {
	nimfr_("del", "tables.nim");
	nimln_(439, "tables.nim");
	del_qvMk5umInCk9bpiZXt9aZZvg(t, key);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void) {
	nimfr_("tables", "tables.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void) {
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_10[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_11[3];
static TNimNode TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7];
NTI_LLQadDAXEvd71UDdEc3lDA_.size = sizeof(tyObject_Table_LLQadDAXEvd71UDdEc3lDA);
NTI_LLQadDAXEvd71UDdEc3lDA_.kind = 18;
NTI_LLQadDAXEvd71UDdEc3lDA_.base = 0;
NTI_LLQadDAXEvd71UDdEc3lDA_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_10[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1];
NTI_g1w83cyyBYiVU9c8WEJWnjQ_.size = sizeof(tyTuple_g1w83cyyBYiVU9c8WEJWnjQ);
NTI_g1w83cyyBYiVU9c8WEJWnjQ_.kind = 18;
NTI_g1w83cyyBYiVU9c8WEJWnjQ_.base = 0;
NTI_g1w83cyyBYiVU9c8WEJWnjQ_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_11[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].offset = offsetof(tyTuple_g1w83cyyBYiVU9c8WEJWnjQ, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_11[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].offset = offsetof(tyTuple_g1w83cyyBYiVU9c8WEJWnjQ, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_11[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].offset = offsetof(tyTuple_g1w83cyyBYiVU9c8WEJWnjQ, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_11[0];
NTI_g1w83cyyBYiVU9c8WEJWnjQ_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2];
NTI_JiteSJxrvz63iP2o9bcn2Sg_.size = sizeof(tySequence_JiteSJxrvz63iP2o9bcn2Sg*);
NTI_JiteSJxrvz63iP2o9bcn2Sg_.kind = 24;
NTI_JiteSJxrvz63iP2o9bcn2Sg_.base = (&NTI_g1w83cyyBYiVU9c8WEJWnjQ_);
NTI_JiteSJxrvz63iP2o9bcn2Sg_.flags = 2;
NTI_JiteSJxrvz63iP2o9bcn2Sg_.marker = Marker_tySequence_JiteSJxrvz63iP2o9bcn2Sg;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].offset = offsetof(tyObject_Table_LLQadDAXEvd71UDdEc3lDA, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].typ = (&NTI_JiteSJxrvz63iP2o9bcn2Sg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_10[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].offset = offsetof(tyObject_Table_LLQadDAXEvd71UDdEc3lDA, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_10[0];
NTI_LLQadDAXEvd71UDdEc3lDA_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0];
NTI_Exo1CrLCLUIZQ4IUZ9aXEGg_.size = sizeof(tyObject_Table_LLQadDAXEvd71UDdEc3lDA*);
NTI_Exo1CrLCLUIZQ4IUZ9aXEGg_.kind = 22;
NTI_Exo1CrLCLUIZQ4IUZ9aXEGg_.base = (&NTI_LLQadDAXEvd71UDdEc3lDA_);
NTI_Exo1CrLCLUIZQ4IUZ9aXEGg_.flags = 2;
NTI_Exo1CrLCLUIZQ4IUZ9aXEGg_.marker = Marker_tyRef_Exo1CrLCLUIZQ4IUZ9aXEGg;
}

